// Converts the world-editor export (src/game/world/authored/career.map.json) into the three
// artifacts the game consumes. Requires the paid Cute Fantasy pack unpacked at
// public/game/cute-fantasy/ (gitignored) — this cannot run in CI.
//
// Run: node scripts/import-map.mjs (npm run map:import), then npm run assets:pack.
//
// Deterministic: no Date.now/Math.random, and convert.js sorts every collection it emits.

import path from 'node:path'
import fs from 'node:fs/promises'
import { existsSync } from 'node:fs'
import sharp from 'sharp'
import { convertMap } from '../src/game/world/authored/convert.js'

const ROOT = process.cwd()
const IN_MAP = path.join(ROOT, 'src', 'game', 'world', 'authored', 'career.map.json')
const OUT_MANIFEST = path.join(ROOT, 'src', 'game', 'assets', 'manifest.authored.js')
const OUT_TILES = path.join(ROOT, 'src', 'game', 'world', 'authored', 'career.tiles.json')
const OUT_PLACEMENTS = path.join(ROOT, 'src', 'data', 'placements.json')
const PACK = path.join(ROOT, 'public', 'game', 'cute-fantasy')

const PACK_ROOT = 'Cute_Fantasy/'
const diskPath = p => path.join(PACK, p.startsWith(PACK_ROOT) ? p.slice(PACK_ROOT.length) : p)

async function dimsCache(map) {
  const paths = new Set()
  for (const l of map.layers) {
    if (l.type === 'objects') for (const o of l.objects || []) paths.add(o.frame.slice(0, o.frame.lastIndexOf('#')))
    else for (const c of l.cells || []) paths.add(c.frame.slice(0, c.frame.lastIndexOf('#')))
  }
  const dims = {}
  for (const p of [...paths].sort()) {
    if (!existsSync(diskPath(p))) continue
    const meta = await sharp(diskPath(p)).metadata()
    dims[p] = { w: meta.width, h: meta.height }
  }
  return dims
}

function manifestModule(manifest) {
  const j = v => JSON.stringify(v, null, 2)
  return `// GENERATED by scripts/import-map.mjs — do not edit by hand.
// Frames sliced out of the authored map (src/game/world/authored/career.map.json).

export const AUTHORED_IMAGES = ${j(manifest.images)}

export const AUTHORED_FRAMES = ${j(manifest.frames)}
`
}

async function main() {
  const map = JSON.parse(await fs.readFile(IN_MAP, 'utf8'))
  const dims = await dimsCache(map)
  const out = convertMap(map, {
    dimsOf: p => dims[p] || { w: 0, h: 0 },
    exists: p => existsSync(diskPath(p)),
  })
  await fs.writeFile(OUT_MANIFEST, manifestModule(out.manifest))
  await fs.writeFile(OUT_TILES, `${JSON.stringify(out.tiles, null, 2)}\n`)
  await fs.writeFile(OUT_PLACEMENTS, `${JSON.stringify(out.placements, null, 2)}\n`)
  const cells = out.tiles.layers.reduce((n, l) => n + l.cells.length, 0)
  console.log(`imported: ${Object.keys(out.manifest.frames).length} frames, ${cells} cells, `
    + `${out.placements.length} placements, ${Object.keys(out.tiles.anchors).length} anchors`)
}

main().catch(e => { console.error(e.message); process.exit(1) })
